heat_template_version: 2015-10-15
description: One Front end Server and 2 Back end Servers

parameters:
    key_pair:
        type: string
        label: Key Pair
        constraints:
            - custom_constraint: nova.keypair
    flavor:
        type: string
        label: Flavor
        constraints:
            - custom_constraint: nova.flavor
    image:
        type: string
        label: Image Name
        constraints:
            - custom_constraint: glance.image
    public_network:
        type: string
        label: Public Network
        constraints:
            - custom_constraint: neutron.network
    zone:
        type: string
        label: Availability Zone
        default: Default
    security_groups:
        type: comma_delimited_list
        label: Security Group(s)
        default: "default"

resources:
    privateNetwork:
        type: OS::Neutron::Net
        properties:
            name: "ccG18PrivateNetwork"
    networkSubnet:
        type: OS::Neutron::Subnet
        properties:
            network_id: { get_resource: privateNetwork }
            cidr: 192.168.2.0/24
            gateway_ip: 192.168.2.1
    floatingIP:
        type: OS::Neutron::FloatingIP
        properties:
            floating_network: {get_param: public_network}
            port_id: {get_attr: [frontEndServer, port]}
    router:
        type: OS::Neutron::Router
        properties:
            external_gateway_info:
                network: { get_param: public_network }
    routerInterface:
        type: OS::Neutron::RouterInterface
        properties:
            router_id: { get_resource: router }
            subnet_id: { get_resource: networkSubnet }
    frontEndSecurityGroup:
        type: OS::Neutron::SecurityGroup
        properties:
            rules:
                - protocol: tcp
                  remote_ip_prefix: 0.0.0.0/0
                  port_range_min: 80
                  port_range_max: 80
                - protocol: tcp
                  remote_ip_prefix: 0.0.0.0/0
                  port_range_min: 22
                  port_range_max: 22
    frontEndServer:
        type: server.yaml
        properties:
            name: ccG18FrontEndServer
            key_pair: {get_param: key_pair}
            flavor: {get_param: flavor}
            image: {get_param: image}
            network: {get_resource: privateNetwork}
            zone: {get_param: zone}
            security_groups: [{get_resource: frontEndSecurityGroup}]
    backEndSecurityGroup:
        type: OS::Neutron::SecurityGroup
        properties:
            rules:
                - protocol: tcp
                  remote_ip_prefix: {get_attr: [frontEndServer, ip]}
                  port_range_min: 22
                  port_range_max: 22
    backEndServers:
        type: OS::Heat::ResourceGroup
        properties:
            count: 2
            resource_def:
                type: server.yaml
                properties:
                    name: ccG18BackEndServer_%index%
                    key_pair: {get_param: key_pair}
                    flavor: {get_param: flavor}
                    image: {get_param: image}
                    network: {get_resource: privateNetwork}
                    zone: {get_param: zone}
                    security_groups: [{get_resource: backEndSecurityGroup}]
outputs:
    floatingIP:
        description: Floating IP of the Front end server
        value: {get_attr: [floatingIP, floating_ip_address]}